fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    concat: 'https://github.com/puppetlabs/puppetlabs-concat.git'
    archive: 'https://github.com/voxpupuli/puppet-archive.git'
    firewall: 'https://github.com/puppetlabs/puppetlabs-firewall.git'
    systemd: 'https://github.com/voxpupuli/puppet-systemd.git'
    keepalived: 'https://github.com/voxpupuli/puppet-keepalived.git'
  symlinks:
    ha_adguard: '#{source_dir}'
